# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        user:
            dynamic: strict
            persistence:
                driver: orm #the driver can be orm, mongodb or phpcr
                model: UserApi\Entity\User
                listener: ~ # by default, listens to "insert", "update" and "delete"
                provider: ~
            settings:
                index:
                    analysis:
                        analyzer:
                            usernameAnalyzer:
                                type: custom
                                tokenizer: usernameTokenizer
                                filter: [ lowercase ]
                        tokenizer:
                            usernameTokenizer:
                                type: "nGram"
                                min_gram: 3
                                max_gram: 5
                number_of_replicas: 1
                number_of_shards: 5
                max_ngram_diff: 2
            properties:
                firstName: { type: text, analyzer: usernameAnalyzer }
                lastName: { type: text }
                phoneNumbers: { type: text }
                id: { type: text }
                createdAt: { type: date }
